### PR TITLE
Basic functionalities

### PR DESCRIPTION
**Pull request by rizakii**
# Functionalities
- Login With username & password
- KiiObject Query
- KiiObject create
# NOTE

**This sample use patched Kii Javascript SDK**

### CODE REVIEW

**Comment by rizakii** [comment]
@yongpingchen please review

**Comment by yongpingchen** [comment]
@rizakii please add description about how to use it in README

**Comment by yongpingchen** [comment]
Better to have basic introduction of your application in README.

**Comment by yongpingchen** [comment]
> Login with accessToken

It is not clear to show it on the app. Please remove it.

**Comment by rizakii** [comment]
@yongpingchen please confirm.

**Comment by yongpingchen** [comment]
Checked. Functions all worked fine now. Please improve README if necessary

**Comment by rizakii** [comment]
@yongpingchen i will add issue for improving README.

**Pull request merged**
